Repository silverstripe/silverstripe-totp-authenticator, pull requests merged in 2019-05, with the labels that each got.

#13 FIX Remove React 15 incompatible Fragment component
  client/dist/js/bundle.js
  client/src/components/TOTP/Register.js
Labels: affects/v4, change/patch

#14 API Renaming login to verify
  client/dist/js/bundle.js
  client/src/boot/registerComponents.js
  client/src/components/TOTP/Register.js
  client/src/components/TOTP/Verify.js
  client/src/components/TOTP/tests/Login-test.js
  client/src/components/TOTP/tests/Register-test.js
  src/Method.php
  src/VerifyHandler.php
  tests/VerifyHandlerTest.php
Labels: affects/v4, change/major

#15 NEW Refactor button list to use the MFA consistent class names
  client/dist/js/bundle.js
  client/src/components/TOTP/Register.js
  client/src/components/TOTP/Verify.js
  client/src/components/TOTP/tests/Register-test.js
  client/src/components/TOTP/tests/Verify-test.js
Labels: affects/v4, change/minor
