Repository silverstripe/silverstripe-totp-authenticator, pull requests merged in 2019-04, with the labels that each got.

#4 NEW RegisterHandler now handles registration of TOTP methods and storage of encrypted TOTP secret on success
  .travis.yml
  README.md
  _config/config.yml
  client/dist/images/totp.svg
  client/dist/js/bundle.js
  client/dist/js/bundle.js.map
  client/src/boot/registerComponents.js
  client/src/components/.gitkeep
  client/src/components/TOTP/Register.js
  composer.json
  package.json
  phpcs.xml.dist
  src/.gitkeep
  src/LoginHandler.php
  src/Method.php
  src/RegisterHandler.php
  tests/RegisterHandlerTest.php
  yarn.lock
Labels: affects/v4, change/major

#6 NEW TOTP Registration screen frontend component and configurable code length
  .gitignore
  client/dist/js/bundle.js
  client/dist/js/bundle.js.map
  client/dist/styles/bundle.css
  client/dist/styles/bundle.css.map
  client/src/bundles/bundle.scss
  client/src/components/TOTP/Register.js
  client/src/components/TOTP/Register.scss
  client/src/components/TOTP/tests/Register-test.js
  client/src/lib/formatCode.js
  client/src/lib/tests/formatCode-test.js
  composer.json
  src/RegisterHandler.php
  tests/RegisterHandlerTest.php
Labels: affects/v4, change/minor

#7 API Add login handler for TOTP and refactor to suit updated MFA interfaces
  README.md
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/boot/registerComponents.js
  client/src/components/TOTP/Login.js
  client/src/components/TOTP/Register.js
  client/src/components/TOTP/Register.scss
  client/src/components/TOTP/tests/Login-test.js
  client/src/components/TOTP/tests/Register-test.js
  client/src/components/TOTP/tests/__mocks__/lib/Injector.js
  package.json
  src/LoginHandler.php
  src/Method.php
  src/RegisterHandler.php
  src/TOTPAware.php
  tests/.gitkeep
  tests/LoginHandlerTest.php
  tests/MethodTest.php
  tests/RegisterHandlerTest.php
Labels: affects/v4, change/major

#8 FIX Error message now comes from the state, and is reset when going back to the scan code screen
  client/dist/js/bundle.js
  client/src/components/TOTP/Register.js
  client/src/components/TOTP/tests/Register-test.js
Labels: affects/v4, change/patch

#9 NEW Add logging for when start() fails in TOTP login
  src/LoginHandler.php
  tests/LoginHandlerTest.php
Labels: affects/v4, change/minor

#11 FIX Update code to use new interface definitions
  src/LoginHandler.php
  src/RegisterHandler.php
  tests/LoginHandlerTest.php
  tests/RegisterHandlerTest.php
Labels: affects/v4, change/major

#10 FIX Pass error message through to frontend on login failure
  client/dist/js/bundle.js
  client/src/components/TOTP/Login.js
  client/src/components/TOTP/tests/Login-test.js
  src/LoginHandler.php
Labels: affects/v4, change/major

#12 FIX Tweak getName to return only the name of the method
  src/RegisterHandler.php
Labels: affects/v4, change/patch
