Repository silverstripe/silverstripe-totp-authenticator, pull requests merged in 2019-08, with the labels that each got.

#32 FIX ensure TOTP icon does not sit over the header
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/TOTP/Register.scss
  client/src/components/TOTP/Verify.js
Labels: affects/v4, change/patch

#31 FIX unsquish text on small viewports
  client/dist/styles/bundle.css
  client/src/components/TOTP/Register.scss
Labels: affects/v4, change/patch

#34 FIX Tweak rendering of QR code in Dark Mode
  client/dist/styles/bundle.css
  client/src/components/TOTP/Register.scss
Labels: affects/v4, change/patch

#35 NEW Add links to userhelp documentation
  src/RegisterHandler.php
Labels: affects/v4, change/minor

#36 FIX Add text class to TOTP verification input field so it renders dark in dark mode
  client/dist/js/bundle.js
  client/src/components/TOTP/Verify.js
Labels: affects/v4, change/patch

#38 FIX TOTP issuer and label are now extensible
  README.md
  src/RegisterHandler.php
Labels: affects/v4, change/patch

#39 FIX TOTP issuer and label are now extensible
  README.md
  src/RegisterHandler.php
Labels: affects/v3, change/patch

#42 FIX Images now resolve correctly when project is installed in a subfolder
  src/Method.php
Labels: affects/v3, change/patch
