Repository silverstripe/silverstripe-totp-authenticator, pull requests merged in 2019-07, with the labels that each got.

#24 DOCS Update readme with some examples and help links, remove unused files
  README.md
  _config.php
  docs/en/readme.md
  phpunit.xml.dist
Labels: affects/v4, type/docs

#25 adjust help link default translation text
  client/dist/js/bundle.js
  client/src/components/TOTP/Register.js
  client/src/components/TOTP/Verify.js
  src/RegisterHandler.php
Labels: affects/v4, change/major

#30 FIX Allow MFA secret to be defined as a PHP constant for SilverStripe 3
  README.md
  src/Method.php
  src/RegisterHandler.php
  src/SecretKeyLoader.php
  src/TOTPAware.php
Labels: affects/v3, change/patch
